### ISSUE TITLE
Critical error in log on Viewer Tournament start of first View Round

### ISSUE THREAD

**Issue by Shebuka** [billw2012/Bannerlord-Twitch#11]
We were doing a Viewer tournament and as soon as I clicked _View round_ a huge call stack of critical error appeared in chat. This is the error from the log:

```
[2022-11-26T01:00:37.1683171+01:00] [TaleWorlds.MountAndBlade.MBDebugManager] [INF]: [BLT][Critical][0037] BLTSummonBehavior.OnAgentBuild: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BLTAdoptAHero.Achievements.AchievementStatsData.<UpdateValue>g__UpdateStatPair|13_0(Statistic stat, Statistic otherStat, <>c__DisplayClass13_0& ) in BLTAdoptAHero\Achievements\AchievementStatsData.cs:line 69
   at BLTAdoptAHero.Achievements.AchievementStatsData.UpdateValue(Statistic type, Guid classId, Int32 amount, Boolean forced) in BLTAdoptAHero\Achievements\AchievementStatsData.cs:line 90
   at BLTAdoptAHero.BLTAdoptAHeroCampaignBehavior.IncreaseStatistic(Hero hero, Statistic statistic, Int32 amount, Boolean forced) in BLTAdoptAHero\Behaviors\BLTAdoptAHeroCampaignBehavior.cs:line 496
   at BLTAdoptAHero.BLTSummonBehavior.AddHeroSummonState(Hero hero, Boolean playerSide, PartyBase party, Boolean forced) in BLTAdoptAHero\Behaviors\BLTSummonBehavior.cs:line 79
   at BLTAdoptAHero.BLTSummonBehavior.<>c__DisplayClass7_0.<OnAgentBuild>b__0() in BLTAdoptAHero\Behaviors\BLTSummonBehavior.cs:line 94
   at BannerlordTwitch.Helpers.AutoMissionBehavior`1.SafeCall(Action a, String fnName) in BannerlordTwitch\Helpers\AutoMissionBehavior.cs:line 20
   
[2022-11-26T01:00:37.1683171+01:00] [TaleWorlds.MountAndBlade.MBDebugManager] [INF]: [BLT][Critical][0037] !!FATAL!!: BLTSummonBehavior.OnAgentBuild: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BLTAdoptAHero.Achievements.AchievementStatsData.<UpdateValue>g__UpdateStatPair|13_0(Statistic stat, Statistic otherStat, <>c__DisplayClass13_0& ) in BLTAdoptAHero\Achievements\AchievementStatsData.cs:line 69
   at BLTAdoptAHero.Achievements.AchievementStatsData.UpdateValue(Statistic type, Guid classId, Int32 amount, Boolean forced) in BLTAdoptAHero\Achievements\AchievementStatsData.cs:line 90
   at BLTAdoptAHero.BLTAdoptAHeroCampaignBehavior.IncreaseStatistic(Hero hero, Statistic statistic, Int32 amount, Boolean forced) in BLTAdoptAHero\Behaviors\BLTAdoptAHeroCampaignBehavior.cs:line 496
   at BLTAdoptAHero.BLTSummonBehavior.AddHeroSummonState(Hero hero, Boolean playerSide, PartyBase party, Boolean forced) in BLTAdoptAHero\Behaviors\BLTSummonBehavior.cs:line 79
   at BLTAdoptAHero.BLTSummonBehavior.<>c__DisplayClass7_0.<OnAgentBuild>b__0() in BLTAdoptAHero\Behaviors\BLTSummonBehavior.cs:line 94
   at BannerlordTwitch.Helpers.AutoMissionBehavior`1.SafeCall(Action a, String fnName) in BannerlordTwitch\Helpers\AutoMissionBehavior.cs:line 20
   
[2022-11-26T01:00:37.1683171+01:00] [TaleWorlds.MountAndBlade.MBDebugManager] [INF]: [BLT][Trace][0037] (repeat) BLTSummonBehavior.OnAgentBuild: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BLTAdoptAHero.Achievements.AchievementStatsData.<UpdateValue>g__UpdateStatPair|13_0(Statistic stat, Statistic otherStat, <>c__DisplayClass13_0& ) in BLTAdoptAHero\Achievements\AchievementStatsData.cs:line 74
   at BLTAdoptAHero.Achievements.AchievementStatsData.UpdateValue(Statistic type, Guid classId, Int32 amount, Boolean forced) in BLTAdoptAHero\Achievements\AchievementStatsData.cs:line 90
   at BLTAdoptAHero.BLTAdoptAHeroCampaignBehavior.IncreaseStatistic(Hero hero, Statistic statistic, Int32 amount, Boolean forced) in BLTAdoptAHero\Behaviors\BLTAdoptAHeroCampaignBehavior.cs:line 496
   at BLTAdoptAHero.BLTSummonBehavior.AddHeroSummonState(Hero hero, Boolean playerSide, PartyBase party, Boolean forced) in BLTAdoptAHero\Behaviors\BLTSummonBehavior.cs:line 79
   at BLTAdoptAHero.BLTSummonBehavior.<>c__DisplayClass7_0.<OnAgentBuild>b__0() in BLTAdoptAHero\Behaviors\BLTSummonBehavior.cs:line 94
   at BannerlordTwitch.Helpers.AutoMissionBehavior`1.SafeCall(Action a, String fnName) in BannerlordTwitch\Helpers\AutoMissionBehavior.cs:line 20
```

I have:
* GoG version of the game v1.0.1.5325
* BLT v4.2.0
* All BLT settings are default

**Comment by billw2012** [comment]
Thanks, it will be fixed in next version
